import type { Metadata, Viewport } from "next";
import "./globals.css";

import ThemeProvider from "@/../src/theme";
import { primaryFont } from "@/../src/theme/typography";
import ProgressBar from "@/../src/components/progress-bar";

import { SettingsProvider } from "@/components/settings";
import Navigation from "@/components/Navigation";

import NextAuthSessionProvider from "@/providers/SessionProvider";

export const viewport: Viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: "NEXT PWA CHAKRA",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    apple: "/icon-512X512.png",
    icon: "/icon-512X512.png",
  },
};

// ----------------------------------------------------------------------

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" className={primaryFont.className}>
      <body>
        <SettingsProvider
          defaultSettings={{
            themeMode: "light", // 'light' | 'dark'
            themeDirection: "ltr", //  'rtl' | 'ltr'
            themeContrast: "default", // 'default' | 'bold'
            themeLayout: "vertical", // 'vertical' | 'horizontal' | 'mini'
            themeColorPresets: "default", // 'default' | 'cyan' | 'purple' | 'blue' | 'orange' | 'red'
            themeStretch: false,
          }}
        >
          <ThemeProvider>
            <ProgressBar />
            <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
